unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -s default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB,alacritty:RGB"
set -g mouse on

set -g status-right '#{prefix_highlight} | %H:%M '
