local colors = {
  background = "#1d2021",
  error = "#ea6962",
  error_container = "#8c1d18",
  inverse_on_surface = "#ddc7a1",
  inverse_primary = "#fabd2f",
  inverse_surface = "#141617",
  on_background = "#ddc7a1",
  on_error = "#601410",
  on_error_container = "#f9dedc",
  on_primary = "#141617",
  on_primary_container = "#ddc7a1",
  on_primary_fixed = "#141617",
  on_primary_fixed_variant = "#141617",
  on_secondary = "#141617",
  on_secondary_container = "#ddc7a1",
  on_secondary_fixed = "#141617",
  on_secondary_fixed_variant = "#141617",
  on_surface = "#ddc7a1",
  on_surface_variant = "#d4be98",
  on_tertiary = "#141617",
  on_tertiary_container = "#ddc7a1",
  on_tertiary_fixed = "#141617",
  on_tertiary_fixed_variant = "#141617",
  outline = "#a89984",
  outline_variant = "#1d2021",
  primary = "#d8a657",
  primary_container = "#6a4f2d",
  primary_fixed = "#6a4f2d",
  primary_fixed_dim = "#d8a657",
  scrim = "#000000",
  secondary = "#e78a4e",
  secondary_container = "#3c3836",
  secondary_fixed = "#e78a4e",
  secondary_fixed_dim = "#e78a4e",
  shadow = "#000000",
  source_color = "#d8a657",
  surface = "#1d2021",
  surface_bright = "#504945",
  surface_container = "#141617",
  surface_container_high = "#282828",
  surface_container_highest = "#3c3836",
  surface_container_low = "#141617",
  surface_container_lowest = "#1d2021",
  surface_dim = "#1d2021",
  surface_tint = "#473c29",
  surface_variant = "#1d2021",
  tertiary = "#e78a4e",
  tertiary_container = "#3c3836",
  tertiary_fixed = "#e78a4e",
  tertiary_fixed_dim = "#e78a4e",
  -- Base16 dark colors
  color0 = "#141617",
  color1 = "#f86155",
  color10 = "#a5ff94",
  color11 = "#ffec94",
  color12 = "#edbe74",
  color13 = "#ffd594",
  color14 = "#ffe4ba",
  color15 = "#fffcf7",
  color2 = "#6bd857",
  color3 = "#ffe257",
  color4 = "#cd943a",
  color5 = "#643d00",
  color6 = "#d8a657",
  color7 = "#e2dcd2",
  color8 = "#8c877f",
  color9 = "#ff958c",
}

local function hex_to_rgb(hex)
    hex = hex:gsub("#", "")
    return tonumber(hex:sub(1, 2), 16), tonumber(hex:sub(3, 4), 16), tonumber(hex:sub(5, 6), 16)
end

local function blend(bg, fg, alpha)
    local br, bg_b, bb = hex_to_rgb(bg)
    local fr, fg_f, fb = hex_to_rgb(fg)
    local r = math.floor(br * (1 - alpha) + fr * alpha)
    local g = math.floor(bg_b * (1 - alpha) + fg_f * alpha)
    local b = math.floor(bb * (1 - alpha) + fb * alpha)
    return string.format("#%02x%02x%02x", r, g, b)
end

local hl = vim.highlight

local function set_hl(group, val)
    if val.link then
        hl.set(group, 0, { link = val.link })
    else
        local guisp = val.guisp
        local sp = val.sp
        val = vim.deepcopy(val)
        val.guisp = nil
        val.sp = nil
        if sp then val.sp = blend(colors.surface, sp, 0.7) end
        if guisp then val.guisp = blend(colors.surface, guisp, 0.7) end
        hl.set(group, 0, val)
    end
end

local theme = {
    editor = {
    Normal = { fg = colors.on_surface, bg = colors.surface },
    NormalNC = { fg = colors.on_surface, bg = colors.surface },
    NormalFloat = { fg = colors.on_surface, bg = colors.surface_container_high },
    FloatBorder = { fg = colors.outline, bg = colors.surface_container_high },
    FloatTitle = { fg = colors.on_surface, bg = colors.surface_container_high },
    Cursor = { fg = colors.inverse_surface, bg = colors.inverse_on_surface },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = colors.surface_container_high },
    CursorLineNr = { fg = colors.on_surface, bg = colors.surface_container_high },
    LineNr = { fg = colors.on_surface_variant, bg = colors.surface },
    LineNrFold = { fg = colors.on_surface_variant, bg = colors.surface },
    FoldColumn = { fg = colors.on_surface_variant, bg = colors.surface },
    SignColumn = { bg = colors.surface },
    Conceal = { fg = colors.on_surface_variant, bg = colors.surface },
    ColorColumn = { bg = colors.surface_container_high },
    CursorColumn = { link = "CursorLine" },
    Directory = { fg = colors.primary, bg = colors.surface },
    EndOfBuffer = { fg = colors.surface, bg = colors.surface },
    ErrorMsg = { fg = colors.on_error, bg = colors.error },
    WinSeparator = { fg = colors.outline_variant, bg = colors.surface },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = colors.on_surface_variant, bg = colors.surface_container_high },
    MatchParen = { fg = colors.primary, bg = colors.surface_container_high, bold = true },
    ModeMsg = { fg = colors.on_surface, bg = colors.surface },
    MsgArea = { fg = colors.on_surface, bg = colors.surface },
    MsgSeparator = { link = "WinSeparator" },
    MoreMsg = { fg = colors.primary },
    NonText = { fg = colors.on_surface_variant, bg = colors.surface },
    NormalSB = { fg = colors.on_surface, bg = colors.surface_container },
    Pmenu = { fg = colors.on_surface, bg = colors.surface_container_high },
    PmenuSel = { fg = colors.on_primary, bg = colors.primary },
    PmenuSbar = { bg = colors.surface_container_high },
    PmenuThumb = { bg = colors.outline },
    Question = { fg = colors.primary },
    QuickFixLine = { fg = colors.on_surface, bg = colors.primary_container },
    Search = { fg = colors.inverse_on_surface, bg = colors.inverse_primary },
    IncSearch = { link = "Search" },
    Substitute = { fg = colors.inverse_on_surface, bg = colors.primary, standout = true },
    SpecialKey = { fg = colors.primary },
    SpellBad = { fg = colors.error, underline = true, sp = colors.error },
    SpellCap = { fg = colors.tertiary, underline = true, sp = colors.tertiary },
    SpellLocal = { fg = colors.secondary, underline = true, sp = colors.secondary },
    SpellRare = { fg = colors.tertiary, underline = true, sp = colors.tertiary },
    StatusLine = { fg = colors.on_surface, bg = colors.surface_container_high },
    StatusLineNC = { fg = colors.on_surface_variant, bg = colors.surface_container_high },
    TabLine = { fg = colors.on_surface_variant, bg = colors.surface_container },
    TabLineFill = { fg = colors.on_surface_variant, bg = colors.surface_container },
    TabLineSel = { fg = colors.on_surface, bg = colors.surface_container_high },
    Title = { fg = colors.on_surface, bold = true },
    Visual = { bg = colors.primary_container },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = colors.on_error, bg = colors.error },
    Whitespace = { fg = colors.outline_variant },
    WildMenu = { fg = colors.on_surface, bg = colors.primary_container },
    winbar = { fg = colors.on_surface, bg = colors.surface },
    winbar_inactive = { fg = colors.on_surface_variant, bg = colors.surface },
    },
    syntax = {
    Comment = { fg = colors.on_surface_variant, italic = true },
    Conditional = { fg = colors.primary },
    Constant = { fg = colors.secondary },
    String = { fg = colors.color10 },
    Number = { fg = colors.color13 },
    Boolean = { fg = colors.secondary },
    Float = { fg = colors.color13 },
    Character = { fg = colors.color9 },
    Identifier = { fg = colors.on_surface },
    Function = { fg = colors.primary },
    Statement = { fg = colors.primary },
    PreProc = { fg = colors.tertiary },
    Include = { link = "PreProc" },
    Define = { link = "PreProc" },
    Macro = { link = "PreProc" },
    PreCondit = { link = "PreProc" },
    Keyword = { fg = colors.primary },
    Repeat = { link = "Keyword" },
    Label = { link = "Keyword" },
    Operator = { fg = colors.on_surface_variant },
    Exception = { fg = colors.error },
    Type = { fg = colors.tertiary },
    StorageClass = { link = "Type" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = colors.secondary },
    SpecialChar = { link = "Special" },
    Tag = { link = "Special" },
    Delimiter = { fg = colors.on_surface_variant },
    SpecialComment = { link = "Comment" },
    Debug = { link = "Special" },
    Tooltip = { fg = colors.on_surface, bg = colors.surface_container_high },
        },
    treesitter = {
    ["@attribute"] = { link = "PreProc" },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "Special" },
    ["@comment"] = { link = "Comment" },
    ["@conditional"] = { link = "Conditional" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "Constant" },
    ["@constructor"] = { fg = colors.tertiary },
    ["@error"] = { fg = colors.error },
    ["@exception"] = { link = "Exception" },
    ["@field"] = { fg = colors.on_surface },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@function.macro"] = { link = "Function" },
    ["@include"] = { link = "Include" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = colors.primary },
    ["@keyword.operator"] = { fg = colors.primary },
    ["@keyword.return"] = { fg = colors.primary },
    ["@label"] = { link = "Label" },
    ["@method"] = { link = "Function" },
    ["@namespace"] = { fg = colors.secondary },
    ["@number"] = { link = "Number" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { fg = colors.color12 },
    ["@property"] = { fg = colors.on_surface },
    ["@punctuation"] = { fg = colors.on_surface_variant },
    ["@punctuation.bracket"] = { fg = colors.on_surface_variant },
    ["@punctuation.delimiter"] = { fg = colors.on_surface_variant },
    ["@punctuation.special"] = { fg = colors.primary },
    ["@repeat"] = { link = "Repeat" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = colors.primary },
    ["@string.regex"] = { link = "String" },
    ["@string.special"] = { link = "Special" },
    ["@symbol"] = { fg = colors.secondary },
    ["@tag"] = { link = "Tag" },
    ["@tag.delimiter"] = { fg = colors.primary },
    ["@text"] = { fg = colors.on_surface },
    ["@text.danger"] = { fg = colors.error, bg = colors.error_container },
    ["@text.diff.add"] = { fg = colors.color10 },
    ["@text.diff.delete"] = { fg = colors.color1 },
    ["@text.emphasis"] = { italic = true },
    ["@text.environment"] = { fg = colors.secondary },
    ["@text.environment.name"] = { fg = colors.tertiary },
    ["@text.literal"] = { link = "String" },
    ["@text.math"] = { fg = colors.secondary },
    ["@text.note"] = { fg = colors.on_surface, bg = colors.primary_container },
    ["@text.note.warning"] = { fg = colors.on_surface, bg = colors.error_container },
    ["@text.reference"] = { fg = colors.secondary },
    ["@text.strike"] = { strikethrough = true },
    ["@text.strong"] = { bold = true },
    ["@text.title"] = { fg = colors.primary, bold = true },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { fg = colors.secondary, underline = true },
    ["@text.warning"] = { fg = colors.on_surface, bg = colors.error_container },
    ["@todo"] = { fg = colors.on_surface, bg = colors.primary_container },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = colors.tertiary },
    ["@type.definition"] = { fg = colors.tertiary },
    ["@type.qualifier"] = { link = "Type" },
    ["@variable"] = { fg = colors.on_surface },
    ["@variable.builtin"] = { fg = colors.secondary },
        },
    lsp = {
    LspCodeLens = { fg = colors.on_surface_variant },
    LspCodeLensSeparator = { fg = colors.on_surface_variant },
    LspCompletionWord = { link = "Search" },
    LspDiagnosticsDefaultError = { link = "Error" },
    LspDiagnosticsDefaultHint = { link = "Hint" },
    LspDiagnosticsDefaultInformation = { link = "Info" },
    LspDiagnosticsDefaultWarning = { link = "Warning" },
    LspDiagnosticsError = { fg = colors.error },
    LspDiagnosticsErrorByteSize = { link = "LspDiagnosticsError" },
    LspDiagnosticsFloatingError = { link = "ErrorFloat" },
    LspDiagnosticsFloatingHint = { link = "HintFloat" },
    LspDiagnosticsFloatingInformation = { link = "InfoFloat" },
    LspDiagnosticsFloatingWarning = { link = "WarningFloat" },
    LspDiagnosticsHint = { fg = colors.primary },
    LspDiagnosticsInformation = { fg = colors.secondary },
    LspDiagnosticsLineDefaultError = { link = "Error" },
    LspDiagnosticsLineDefaultHint = { link = "Hint" },
    LspDiagnosticsLineDefaultInformation = { link = "Info" },
    LspDiagnosticsLineDefaultWarning = { link = "Warning" },
    LspDiagnosticsSignDefaultError = { link = "LspDiagnosticsSignError" },
    LspDiagnosticsSignDefaultHint = { link = "LspDiagnosticsSignHint" },
    LspDiagnosticsSignDefaultInformation = { link = "LspDiagnosticsSignInformation" },
    LspDiagnosticsSignDefaultWarning = { link = "LspDiagnosticsSignWarning" },
    LspDiagnosticsSignError = { fg = colors.error },
    LspDiagnosticsSignHint = { fg = colors.primary },
    LspDiagnosticsSignInformation = { fg = colors.secondary },
    LspDiagnosticsSignWarning = { fg = colors.color4 },
    LspDiagnosticsUnderlineError = { undercurl = true, sp = colors.error },
    LspDiagnosticsUnderlineHint = { undercurl = true, sp = colors.primary },
    LspDiagnosticsUnderlineInformation = { undercurl = true, sp = colors.secondary },
    LspDiagnosticsUnderlineWarning = { undercurl = true, sp = colors.color4 },
    LspDiagnosticsVirtualTextDefaultError = { link = "LspDiagnosticsError" },
    LspDiagnosticsVirtualTextDefaultHint = { link = "LspDiagnosticsHint" },
    LspDiagnosticsVirtualTextDefaultInformation = { link = "LspDiagnosticsInformation" },
    LspDiagnosticsVirtualTextDefaultWarning = { link = "LspDiagnosticsWarning" },
    LspDiagnosticsVirtualTextError = { fg = colors.error },
    LspDiagnosticsVirtualTextHint = { fg = colors.primary },
    LspDiagnosticsVirtualTextInformation = { fg = colors.secondary },
    LspDiagnosticsVirtualTextWarning = { fg = colors.color4 },
    LspReferenceRead = { bg = colors.surface_container_high },
    LspReferenceText = { bg = colors.surface_container_high },
    LspReferenceWrite = { bg = colors.surface_container_high },
    LspSignatureActiveParameter = { link = "Search" },
        },
    diagnostics = {
    DiagnosticDefaultError = { link = "Error" },
    DiagnosticDefaultHint = { link = "Hint" },
    DiagnosticDefaultInformation = { link = "Info" },
    DiagnosticDefaultWarn = { link = "Warning" },
    DiagnosticError = { link = "Error" },
    DiagnosticFloatingError = { link = "ErrorFloat" },
    DiagnosticFloatingHint = { link = "HintFloat" },
    DiagnosticFloatingInformation = { link = "InfoFloat" },
    DiagnosticFloatingWarn = { link = "WarningFloat" },
    DiagnosticHint = { fg = colors.primary },
    DiagnosticInformation = { fg = colors.secondary },
    DiagnosticOk = { fg = colors.color10 },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.primary },
    DiagnosticUnderlineInformation = { undercurl = true, sp = colors.secondary },
    DiagnosticUnderlineOk = { undercurl = true, sp = colors.color10 },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.color4 },
    DiagnosticUnnecessary = { fg = colors.on_surface_variant, underline = true },
    DiagnosticVirtualTextError = { link = "LspDiagnosticsVirtualTextError" },
    DiagnosticVirtualTextHint = { link = "LspDiagnosticsVirtualTextHint" },
    DiagnosticVirtualTextInformation = { link = "LspDiagnosticsVirtualTextInformation" },
    DiagnosticVirtualTextOk = { fg = colors.color10 },
    DiagnosticVirtualTextWarn = { link = "LspDiagnosticsVirtualTextWarning" },
    DiagnosticWarn = { fg = colors.color4 },
    Error = { fg = colors.error },
    ErrorFloat = { fg = colors.on_error, bg = colors.error },
    Hint = { fg = colors.primary },
    HintFloat = { fg = colors.on_primary, bg = colors.primary },
    Info = { fg = colors.secondary },
    InfoFloat = { fg = colors.on_secondary, bg = colors.secondary },
    Warning = { fg = colors.color4 },
    WarningFloat = { fg = colors.on_background, bg = colors.color4 },
        },
    diff = {
    diffAdded = { fg = colors.color10 },
    diffChanged = { fg = colors.color4 },
    diffDeleted = { fg = colors.color1 },
    diffAddedDouble = { link = "diffAdded" },
    diffAddedGutter = { link = "diffAdded" },
    diffBase = { fg = colors.on_surface },
    diffChangedGutter = { link = "diffChanged" },
    diffCommon = { fg = colors.on_surface },
    diffDeletedGutter = { link = "diffDeleted" },
    diffDiffAdded = { link = "diffAdded" },
    diffDiffDeleted = { link = "diffDeleted" },
    diffFile = { fg = colors.primary },
    diffFileName = { fg = colors.primary },
    diffGutterAddedLine = { bg = colors.color10, blend = 20 },
    diffGutterChangedLine = { bg = colors.color4, blend = 20 },
    diffGutterDeletedLine = { bg = colors.color1, blend = 20 },
    diffGutterUntracked = { fg = colors.on_surface_variant },
    diffIdentifier = { fg = colors.primary, bold = true },
    diffIndexLine = { fg = colors.on_surface_variant },
    diffIndexLineDeleted = { link = "diffDeleted" },
    diffIndexLineInserted = { link = "diffAdded" },
    diffLine = { fg = colors.primary },
    diffLineAdded = { link = "diffAdded" },
    diffLineDeleted = { link = "diffDeleted" },
    diffLocation = { fg = colors.primary },
    diffNewFile = { fg = colors.color10 },
    diffNoChanges = { fg = colors.on_surface },
    diffOldFile = { fg = colors.color1 },
    diffOnly = { fg = colors.primary },
    diffRemoved = { link = "diffDeleted" },
    diffResourceAdd = { link = "diffAdded" },
    diffResourceChange = { link = "diffChanged" },
    diffResourceDelete = { link = "diffDeleted" },
    diffResourceHeader = { fg = colors.primary, bold = true },
    diffResult = { fg = colors.on_surface },
    diffStatAdd = { link = "diffAdded" },
    diffStatChange = { link = "diffChanged" },
    diffStatDelete = { link = "diffDeleted" },
    diffSubtextNew = { fg = colors.color4 },
    diffSubtextOld = { fg = colors.color1 },
    diffUntracked = { fg = colors.color4 },
    diffUntrackedFile = { fg = colors.color4 },
        },
    lualine = {
        normal = {
            a = { bg = colors.primary, fg = colors.on_primary },
            b = { bg = colors.surface_container_high, fg = colors.on_surface },
            c = { bg = colors.surface, fg = colors.on_surface },
        },
        insert = {
            a = { bg = colors.tertiary, fg = colors.on_tertiary },
            b = { bg = colors.surface_container_high, fg = colors.on_surface },
            c = { bg = colors.surface, fg = colors.on_surface },
        },
        visual = {
            a = { bg = colors.secondary, fg = colors.on_secondary },
            b = { bg = colors.surface_container_high, fg = colors.on_surface },
            c = { bg = colors.surface, fg = colors.on_surface },
        },
        command = {
            a = { bg = colors.primary, fg = colors.on_primary },
            b = { bg = colors.surface_container_high, fg = colors.on_surface },
            c = { bg = colors.surface, fg = colors.on_surface },
        },
        replace = {
            a = { bg = colors.error, fg = colors.on_error },
            b = { bg = colors.surface_container_high, fg = colors.on_surface },
            c = { bg = colors.surface, fg = colors.on_surface },
        },
        inactive = {
            a = { bg = colors.surface_dim, fg = colors.on_surface_variant },
            b = { bg = colors.surface_dim, fg = colors.on_surface_variant },
            c = { bg = colors.surface, fg = colors.on_surface_variant },
        },
    },
}

return theme, set_hl
