gui:
  theme:
    activeBorderColor:
      - '#bdc2ff'
      - bold
    inactiveBorderColor:
      - '#91909a'
    optionsTextColor:
      - '#bdc2ff'
    selectedLineBgColor:
      - '#1f1f25'
    cherryPickedCommitBgColor:
      - '#131318'
    cherryPickedCommitFgColor:
      - '#7fff95'
    unstagedChangesColor:
      - '#ff9fb7'
    defaultFgColor:
      - '#e4e1e9'
    searchingActiveBorderColor:
      - '#bdc2ff'
  showIcons: true
  nerdFontsVersion: "3"
