gui:
  theme:
    activeBorderColor:
      - '#c2c1ff'
      - bold
    inactiveBorderColor:
      - '#918f9a'
    optionsTextColor:
      - '#c2c1ff'
    selectedLineBgColor:
      - '#1f1f25'
    cherryPickedCommitBgColor:
      - '#131318'
    cherryPickedCommitFgColor:
      - '#7fff96'
    unstagedChangesColor:
      - '#ff9fb6'
    defaultFgColor:
      - '#e5e1e9'
    searchingActiveBorderColor:
      - '#c2c1ff'
  showIcons: true
  nerdFontsVersion: "3"
