gui:
  theme:
    activeBorderColor:
      - '#fabd2f' # Yellow
      - bold
    inactiveBorderColor:
      - '#928374' # Gray
    optionsTextColor:
      - '#fabd2f' # Yellow
    selectedLineBgColor:
      - '#3c3836' # Dark brown
    cherryPickedCommitBgColor:
      - '#504945' # Medium brown
    cherryPickedCommitFgColor:
      - '#b8bb26' # Green
    unstagedChangesColor:
      - '#fb4934' # Red
    defaultFgColor:
      - '#ebdbb2' # Light cream
    searchingActiveBorderColor:
      - '#fabd2f' # Yellow
  showIcons: true
  nerdFontsVersion: "3"
