gui:
  theme:
    activeBorderColor:
      - '#89b4fa' # Blue
      - bold
    inactiveBorderColor:
      - '#a6adc8' # Light gray/blue
    optionsTextColor:
      - '#89b4fa' # Blue
    selectedLineBgColor:
      - '#313244' # Dark gray/blue
    cherryPickedCommitBgColor:
      - '#45475a' # Darker gray/blue
    cherryPickedCommitFgColor:
      - '#89b4fa' # Blue
    unstagedChangesColor:
      - '#f38ba8' # Pinkish-red
    defaultFgColor:
      - '#cdd6f4' # Off-white
    searchingActiveBorderColor:
      - '#f9e2af' # Yellowish
  showIcons: true
  nerdFontsVersion: "3"
