[ids]
*

[main]
capslock = overload(nav, esc)

[nav]
# hjkl movement
h = left
j = down
k = up
l = right

# word jump
e = C-right
w = C-left

# select word
v = C-S-right
c = C-S-left

# paging
u = pageup
d = pagedown

# line start / end
f = home
slash = end     # code:47 ใน hyprland = /

# delete
o = backspace
i = C-backspace
p = delete

# misc
q = esc
n = A-left      # alt + left (back)
x = C-w
r = C-r
t = C-t

# tabs
comma = C-tab           # code:60
dot   = C-S-tab         # code:59

# move lines (editor dependent)
m = C-S-up               # code:34
period = C-S-down        # code:35
